*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZINTCOMP_MV_005.................................*
FORM GET_DATA_ZINTCOMP_MV_005.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZINTCOMP_M_005 WHERE
(VIM_WHERETAB) .
    CLEAR ZINTCOMP_MV_005 .
ZINTCOMP_MV_005-MANDT =
ZINTCOMP_M_005-MANDT .
ZINTCOMP_MV_005-BUKRS =
ZINTCOMP_M_005-BUKRS .
ZINTCOMP_MV_005-BKLAS =
ZINTCOMP_M_005-BKLAS .
ZINTCOMP_MV_005-MASRAF_TIP =
ZINTCOMP_M_005-MASRAF_TIP .
ZINTCOMP_MV_005-MASRAF_HESAP =
ZINTCOMP_M_005-MASRAF_HESAP .
ZINTCOMP_MV_005-ARA_HESAP =
ZINTCOMP_M_005-ARA_HESAP .
ZINTCOMP_MV_005-KOSTL =
ZINTCOMP_M_005-KOSTL .
ZINTCOMP_MV_005-BUKRSZ =
ZINTCOMP_M_005-BUKRSZ .
<VIM_TOTAL_STRUC> = ZINTCOMP_MV_005.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZINTCOMP_MV_005 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZINTCOMP_MV_005.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZINTCOMP_MV_005-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZINTCOMP_M_005 WHERE
  BUKRS = ZINTCOMP_MV_005-BUKRS AND
  BUKRSZ = ZINTCOMP_MV_005-BUKRSZ AND
  BKLAS = ZINTCOMP_MV_005-BKLAS AND
  MASRAF_TIP = ZINTCOMP_MV_005-MASRAF_TIP .
    IF SY-SUBRC = 0.
    DELETE ZINTCOMP_M_005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZINTCOMP_M_005 WHERE
  BUKRS = ZINTCOMP_MV_005-BUKRS AND
  BUKRSZ = ZINTCOMP_MV_005-BUKRSZ AND
  BKLAS = ZINTCOMP_MV_005-BKLAS AND
  MASRAF_TIP = ZINTCOMP_MV_005-MASRAF_TIP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZINTCOMP_M_005.
    ENDIF.
ZINTCOMP_M_005-MANDT =
ZINTCOMP_MV_005-MANDT .
ZINTCOMP_M_005-BUKRS =
ZINTCOMP_MV_005-BUKRS .
ZINTCOMP_M_005-BKLAS =
ZINTCOMP_MV_005-BKLAS .
ZINTCOMP_M_005-MASRAF_TIP =
ZINTCOMP_MV_005-MASRAF_TIP .
ZINTCOMP_M_005-MASRAF_HESAP =
ZINTCOMP_MV_005-MASRAF_HESAP .
ZINTCOMP_M_005-ARA_HESAP =
ZINTCOMP_MV_005-ARA_HESAP .
ZINTCOMP_M_005-KOSTL =
ZINTCOMP_MV_005-KOSTL .
ZINTCOMP_M_005-BUKRSZ =
ZINTCOMP_MV_005-BUKRSZ .
    IF SY-SUBRC = 0.
    UPDATE ZINTCOMP_M_005 ##WARN_OK.
    ELSE.
    INSERT ZINTCOMP_M_005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZINTCOMP_MV_005-UPD_FLAG,
STATUS_ZINTCOMP_MV_005-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZINTCOMP_MV_005.
  SELECT SINGLE * FROM ZINTCOMP_M_005 WHERE
BUKRS = ZINTCOMP_MV_005-BUKRS AND
BUKRSZ = ZINTCOMP_MV_005-BUKRSZ AND
BKLAS = ZINTCOMP_MV_005-BKLAS AND
MASRAF_TIP = ZINTCOMP_MV_005-MASRAF_TIP .
ZINTCOMP_MV_005-MANDT =
ZINTCOMP_M_005-MANDT .
ZINTCOMP_MV_005-BUKRS =
ZINTCOMP_M_005-BUKRS .
ZINTCOMP_MV_005-BKLAS =
ZINTCOMP_M_005-BKLAS .
ZINTCOMP_MV_005-MASRAF_TIP =
ZINTCOMP_M_005-MASRAF_TIP .
ZINTCOMP_MV_005-MASRAF_HESAP =
ZINTCOMP_M_005-MASRAF_HESAP .
ZINTCOMP_MV_005-ARA_HESAP =
ZINTCOMP_M_005-ARA_HESAP .
ZINTCOMP_MV_005-KOSTL =
ZINTCOMP_M_005-KOSTL .
ZINTCOMP_MV_005-BUKRSZ =
ZINTCOMP_M_005-BUKRSZ .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZINTCOMP_MV_005 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZINTCOMP_MV_005-BUKRS TO
ZINTCOMP_M_005-BUKRS .
MOVE ZINTCOMP_MV_005-BUKRSZ TO
ZINTCOMP_M_005-BUKRSZ .
MOVE ZINTCOMP_MV_005-BKLAS TO
ZINTCOMP_M_005-BKLAS .
MOVE ZINTCOMP_MV_005-MASRAF_TIP TO
ZINTCOMP_M_005-MASRAF_TIP .
MOVE ZINTCOMP_MV_005-MANDT TO
ZINTCOMP_M_005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZINTCOMP_M_005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZINTCOMP_M_005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZINTCOMP_M_005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
