*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZINTCOMP_MV_006.................................*
FORM GET_DATA_ZINTCOMP_MV_006.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZINTCOMP_M_006 WHERE
(VIM_WHERETAB) .
    CLEAR ZINTCOMP_MV_006 .
ZINTCOMP_MV_006-MANDT =
ZINTCOMP_M_006-MANDT .
ZINTCOMP_MV_006-BUKRS =
ZINTCOMP_M_006-BUKRS .
ZINTCOMP_MV_006-KAYIT_TUR =
ZINTCOMP_M_006-KAYIT_TUR .
ZINTCOMP_MV_006-TERS_KAYIT =
ZINTCOMP_M_006-TERS_KAYIT .
ZINTCOMP_MV_006-KONTROL_SIRA =
ZINTCOMP_M_006-KONTROL_SIRA .
ZINTCOMP_MV_006-KAYIT_ADET =
ZINTCOMP_M_006-KAYIT_ADET .
ZINTCOMP_MV_006-ONCEKI_BELGE =
ZINTCOMP_M_006-ONCEKI_BELGE .
ZINTCOMP_MV_006-ONC_BELGE_KONTROL =
ZINTCOMP_M_006-ONC_BELGE_KONTROL .
ZINTCOMP_MV_006-MSGNO =
ZINTCOMP_M_006-MSGNO .
ZINTCOMP_MV_006-BUKRSZ =
ZINTCOMP_M_006-BUKRSZ .
<VIM_TOTAL_STRUC> = ZINTCOMP_MV_006.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZINTCOMP_MV_006 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZINTCOMP_MV_006.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZINTCOMP_MV_006-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZINTCOMP_M_006 WHERE
  BUKRS = ZINTCOMP_MV_006-BUKRS AND
  BUKRSZ = ZINTCOMP_MV_006-BUKRSZ AND
  KAYIT_TUR = ZINTCOMP_MV_006-KAYIT_TUR AND
  TERS_KAYIT = ZINTCOMP_MV_006-TERS_KAYIT AND
  KONTROL_SIRA = ZINTCOMP_MV_006-KONTROL_SIRA .
    IF SY-SUBRC = 0.
    DELETE ZINTCOMP_M_006 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZINTCOMP_M_006 WHERE
  BUKRS = ZINTCOMP_MV_006-BUKRS AND
  BUKRSZ = ZINTCOMP_MV_006-BUKRSZ AND
  KAYIT_TUR = ZINTCOMP_MV_006-KAYIT_TUR AND
  TERS_KAYIT = ZINTCOMP_MV_006-TERS_KAYIT AND
  KONTROL_SIRA = ZINTCOMP_MV_006-KONTROL_SIRA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZINTCOMP_M_006.
    ENDIF.
ZINTCOMP_M_006-MANDT =
ZINTCOMP_MV_006-MANDT .
ZINTCOMP_M_006-BUKRS =
ZINTCOMP_MV_006-BUKRS .
ZINTCOMP_M_006-KAYIT_TUR =
ZINTCOMP_MV_006-KAYIT_TUR .
ZINTCOMP_M_006-TERS_KAYIT =
ZINTCOMP_MV_006-TERS_KAYIT .
ZINTCOMP_M_006-KONTROL_SIRA =
ZINTCOMP_MV_006-KONTROL_SIRA .
ZINTCOMP_M_006-KAYIT_ADET =
ZINTCOMP_MV_006-KAYIT_ADET .
ZINTCOMP_M_006-ONCEKI_BELGE =
ZINTCOMP_MV_006-ONCEKI_BELGE .
ZINTCOMP_M_006-ONC_BELGE_KONTROL =
ZINTCOMP_MV_006-ONC_BELGE_KONTROL .
ZINTCOMP_M_006-MSGNO =
ZINTCOMP_MV_006-MSGNO .
ZINTCOMP_M_006-BUKRSZ =
ZINTCOMP_MV_006-BUKRSZ .
    IF SY-SUBRC = 0.
    UPDATE ZINTCOMP_M_006 ##WARN_OK.
    ELSE.
    INSERT ZINTCOMP_M_006 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZINTCOMP_MV_006-UPD_FLAG,
STATUS_ZINTCOMP_MV_006-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZINTCOMP_MV_006.
  SELECT SINGLE * FROM ZINTCOMP_M_006 WHERE
BUKRS = ZINTCOMP_MV_006-BUKRS AND
BUKRSZ = ZINTCOMP_MV_006-BUKRSZ AND
KAYIT_TUR = ZINTCOMP_MV_006-KAYIT_TUR AND
TERS_KAYIT = ZINTCOMP_MV_006-TERS_KAYIT AND
KONTROL_SIRA = ZINTCOMP_MV_006-KONTROL_SIRA .
ZINTCOMP_MV_006-MANDT =
ZINTCOMP_M_006-MANDT .
ZINTCOMP_MV_006-BUKRS =
ZINTCOMP_M_006-BUKRS .
ZINTCOMP_MV_006-KAYIT_TUR =
ZINTCOMP_M_006-KAYIT_TUR .
ZINTCOMP_MV_006-TERS_KAYIT =
ZINTCOMP_M_006-TERS_KAYIT .
ZINTCOMP_MV_006-KONTROL_SIRA =
ZINTCOMP_M_006-KONTROL_SIRA .
ZINTCOMP_MV_006-KAYIT_ADET =
ZINTCOMP_M_006-KAYIT_ADET .
ZINTCOMP_MV_006-ONCEKI_BELGE =
ZINTCOMP_M_006-ONCEKI_BELGE .
ZINTCOMP_MV_006-ONC_BELGE_KONTROL =
ZINTCOMP_M_006-ONC_BELGE_KONTROL .
ZINTCOMP_MV_006-MSGNO =
ZINTCOMP_M_006-MSGNO .
ZINTCOMP_MV_006-BUKRSZ =
ZINTCOMP_M_006-BUKRSZ .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZINTCOMP_MV_006 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZINTCOMP_MV_006-BUKRS TO
ZINTCOMP_M_006-BUKRS .
MOVE ZINTCOMP_MV_006-BUKRSZ TO
ZINTCOMP_M_006-BUKRSZ .
MOVE ZINTCOMP_MV_006-KAYIT_TUR TO
ZINTCOMP_M_006-KAYIT_TUR .
MOVE ZINTCOMP_MV_006-TERS_KAYIT TO
ZINTCOMP_M_006-TERS_KAYIT .
MOVE ZINTCOMP_MV_006-KONTROL_SIRA TO
ZINTCOMP_M_006-KONTROL_SIRA .
MOVE ZINTCOMP_MV_006-MANDT TO
ZINTCOMP_M_006-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZINTCOMP_M_006'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZINTCOMP_M_006 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZINTCOMP_M_006'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
